//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisnessLogical
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRAINDICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRAINDICATION()
        {
            this.CONTRAINDICATIONS_has_MEDICAMENT = new HashSet<CONTRAINDICATIONS_has_MEDICAMENT>();
        }
    
        public int C_ID { get; set; }
        public string C_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAINDICATIONS_has_MEDICAMENT> CONTRAINDICATIONS_has_MEDICAMENT { get; set; }
    }
}
