//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisnessLogical
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENT_has_ATX
    {
        public int ID { get; set; }
        public Nullable<int> M_ID { get; set; }
        public Nullable<int> A_ID { get; set; }
    
        public virtual ATX ATX { get; set; }
        public virtual MEDICAMENT MEDICAMENT { get; set; }
    }
}
