//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisnessLogical
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICAMENT()
        {
            this.CONTRAINDICATIONS_has_MEDICAMENT = new HashSet<CONTRAINDICATIONS_has_MEDICAMENT>();
            this.MEDICAMENT_has_SYMPTOMS = new HashSet<MEDICAMENT_has_SYMPTOMS>();
            this.MEDICAMENTOS_has_GROUP = new HashSet<MEDICAMENTOS_has_GROUP>();
            this.Sells = new HashSet<Sell>();
            this.SIDE_EFFECT_has_MEDICAMENT = new HashSet<SIDE_EFFECT_has_MEDICAMENT>();
            this.MEDICAMENT_HAS_ACTIVESUBSTANCE = new HashSet<MEDICAMENT_HAS_ACTIVESUBSTANCE>();
            this.MEDICAMENT_has_ATX = new HashSet<MEDICAMENT_has_ATX>();
        }
    
        public int M_ID { get; set; }
        public string M_NAME { get; set; }
        public string M_COMPOSITION { get; set; }
        public string M_PHARMACOLOGICAL__ACTION { get; set; }
        public string M_METHOD_USE_DOSAGE { get; set; }
        public string M_DRUG_INTERACTIONS { get; set; }
        public string M_SPECIFIC_INDUCTION { get; set; }
        public string M_STORAGE_CONDITIONS { get; set; }
        public string M_EXPITY_DATE { get; set; }
        public string M_AVAILABILITY_PRESCRIPTIONS { get; set; }
        public string M_APPEARANCE { get; set; }
        public string M_OVERDOSE { get; set; }
        public int MR_ID { get; set; }
        public Nullable<decimal> M_PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRAINDICATIONS_has_MEDICAMENT> CONTRAINDICATIONS_has_MEDICAMENT { get; set; }
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAMENT_has_SYMPTOMS> MEDICAMENT_has_SYMPTOMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAMENTOS_has_GROUP> MEDICAMENTOS_has_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIDE_EFFECT_has_MEDICAMENT> SIDE_EFFECT_has_MEDICAMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAMENT_HAS_ACTIVESUBSTANCE> MEDICAMENT_HAS_ACTIVESUBSTANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAMENT_has_ATX> MEDICAMENT_has_ATX { get; set; }
    }
}
