//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BisnessLogical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller()
        {
            this.CHECKs = new HashSet<CHECK>();
        }
    
        public int S_ID { get; set; }
        public string S_FIRST_NAME { get; set; }
        public string S_LAST_NAME { get; set; }
        public string S_PATRONYMIC { get; set; }
        public string S_POST { get; set; }
        public string S_PHONE { get; set; }
        public string S_ADRESS { get; set; }
        public string S_PASSWORD { get; set; }
        public string S_LOGIN { get; set; }
        public int AS_ID { get; set; }
    
        public virtual Access_Seller Access_Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK> CHECKs { get; set; }
    }
}
